name: TestFlight Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    if: github.repository == 'realagiorganization/ish'
    runs-on: macos-15
    timeout-minutes: 720
    env:
      RELEASE_NOTES: ${{ github.event.release.body }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install deps
        run: |
          brew install ninja lld llvm meson
          bundle install

      - name: Run unit/UI tests
        run: |
          xcodebuild \
            -project iSH.xcodeproj \
            -scheme iSH \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            test

      - name: Fastlane release to TestFlight
        timeout-minutes: 720
        run: bundle exec fastlane release_testflight changelog:"${RELEASE_NOTES}"
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GITHUB_AUTH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSPHRASE }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
          FASTLANE_SKIP_UPDATE_CHECK: 1

      - uses: actions/upload-artifact@v4
        with:
          name: TestFlight Release IPA
          path: |
            iSH-Release.ipa
